import { z } from "zod";
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "staging", "production"]>>;
    DATABASE_URL: z.ZodString;
    DATABASE_URL_TEST: z.ZodOptional<z.ZodString>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    JWT_SECRET: z.ZodString;
    JWT_ACCESS_TOKEN_EXPIRY: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_TOKEN_EXPIRY: z.ZodDefault<z.ZodString>;
    API_URL: z.ZodOptional<z.ZodString>;
    FRONTEND_URL: z.ZodOptional<z.ZodString>;
    PORT: z.ZodDefault<z.ZodString>;
    BACKEND_PORT: z.ZodOptional<z.ZodString>;
    CORS_ORIGIN: z.ZodOptional<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
    WORKER_CONCURRENCY: z.ZodPipeline<z.ZodEffects<z.ZodDefault<z.ZodString>, number, string | undefined>, z.ZodNumber>;
    NEXT_PUBLIC_API_BASE_URL: z.ZodDefault<z.ZodString>;
    EMAIL_FROM_DEFAULT: z.ZodOptional<z.ZodString>;
    EMAIL_TRANSPORT: z.ZodDefault<z.ZodEnum<["stub", "smtp"]>>;
    SMTP_HOST: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodString>;
    SMTP_USER: z.ZodOptional<z.ZodString>;
    SMTP_PASSWORD: z.ZodOptional<z.ZodString>;
    SMTP_FROM: z.ZodOptional<z.ZodString>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    STORAGE_TYPE: z.ZodDefault<z.ZodEnum<["local", "s3", "gcs", "azure"]>>;
    STORAGE_BASE_PATH: z.ZodDefault<z.ZodString>;
    STORAGE_BUCKET_NAME: z.ZodOptional<z.ZodString>;
    STORAGE_MAX_FILE_SIZE: z.ZodDefault<z.ZodString>;
    STORAGE_ALLOWED_MIME_TYPES: z.ZodDefault<z.ZodString>;
    REPORTING_ENABLED: z.ZodEffects<z.ZodDefault<z.ZodString>, boolean, string | undefined>;
    PDF_EXPORT_ENABLED: z.ZodEffects<z.ZodDefault<z.ZodString>, boolean, string | undefined>;
    EXCEL_EXPORT_ENABLED: z.ZodEffects<z.ZodDefault<z.ZodString>, boolean, string | undefined>;
    SCHEDULED_REPORTS_ENABLED: z.ZodEffects<z.ZodDefault<z.ZodString>, boolean, string | undefined>;
}, "strip", z.ZodTypeAny, {
    DATABASE_URL: string;
    NODE_ENV: "development" | "staging" | "production";
    JWT_SECRET: string;
    JWT_ACCESS_TOKEN_EXPIRY: string;
    JWT_REFRESH_TOKEN_EXPIRY: string;
    PORT: string;
    LOG_LEVEL: "info" | "warn" | "error" | "debug";
    WORKER_CONCURRENCY: number;
    NEXT_PUBLIC_API_BASE_URL: string;
    EMAIL_TRANSPORT: "stub" | "smtp";
    STORAGE_TYPE: "local" | "s3" | "gcs" | "azure";
    STORAGE_BASE_PATH: string;
    STORAGE_MAX_FILE_SIZE: string;
    STORAGE_ALLOWED_MIME_TYPES: string;
    REPORTING_ENABLED: boolean;
    PDF_EXPORT_ENABLED: boolean;
    EXCEL_EXPORT_ENABLED: boolean;
    SCHEDULED_REPORTS_ENABLED: boolean;
    DATABASE_URL_TEST?: string | undefined;
    REDIS_URL?: string | undefined;
    API_URL?: string | undefined;
    FRONTEND_URL?: string | undefined;
    BACKEND_PORT?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    EMAIL_FROM_DEFAULT?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: string | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
    SMTP_FROM?: string | undefined;
    SENTRY_DSN?: string | undefined;
    STORAGE_BUCKET_NAME?: string | undefined;
}, {
    DATABASE_URL: string;
    JWT_SECRET: string;
    NODE_ENV?: "development" | "staging" | "production" | undefined;
    DATABASE_URL_TEST?: string | undefined;
    REDIS_URL?: string | undefined;
    JWT_ACCESS_TOKEN_EXPIRY?: string | undefined;
    JWT_REFRESH_TOKEN_EXPIRY?: string | undefined;
    API_URL?: string | undefined;
    FRONTEND_URL?: string | undefined;
    PORT?: string | undefined;
    BACKEND_PORT?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    LOG_LEVEL?: "info" | "warn" | "error" | "debug" | undefined;
    WORKER_CONCURRENCY?: string | undefined;
    NEXT_PUBLIC_API_BASE_URL?: string | undefined;
    EMAIL_FROM_DEFAULT?: string | undefined;
    EMAIL_TRANSPORT?: "stub" | "smtp" | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: string | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
    SMTP_FROM?: string | undefined;
    SENTRY_DSN?: string | undefined;
    STORAGE_TYPE?: "local" | "s3" | "gcs" | "azure" | undefined;
    STORAGE_BASE_PATH?: string | undefined;
    STORAGE_BUCKET_NAME?: string | undefined;
    STORAGE_MAX_FILE_SIZE?: string | undefined;
    STORAGE_ALLOWED_MIME_TYPES?: string | undefined;
    REPORTING_ENABLED?: string | undefined;
    PDF_EXPORT_ENABLED?: string | undefined;
    EXCEL_EXPORT_ENABLED?: string | undefined;
    SCHEDULED_REPORTS_ENABLED?: string | undefined;
}>;
export type EnvConfig = z.infer<typeof envSchema>;
export declare function getConfig(): EnvConfig;
export declare function clearConfigCache(): void;
export declare function validateEnv(): void;
export {};
//# sourceMappingURL=index.d.ts.map